{"Year": 2000, "Title": "Martin C. Emele, Michael Dorna, Anke L\u00fcdeling, Heike Zinsmeister, Christian Rohrer. Semantic-Based Transfer.. In Verbmobil: Foundations of Speech-to-Speech Translation. Series: \"Artificial Intelligence\". Page 361.  (Postscript, 18 pages)"}
{"Year": 2000, "Title": "Michael Schiehlen. Semantic Construction. In Verbmobil: Foundations of Speech-to-Speech Translation. Series: \"Artificial Intelligence\". Pages 200-215.  (Postscript, 16 pages)"}
{"Year": 2000, "Title": "Michael Schiehlen, Johan Bos, Michael Dorna. Verbmobil Interface Terms (VITs). In Verbmobil: Foundations of Speech-to-Speech Translation. Series: \"Artificial Intelligence\". Pages 183-199.  (Postscript, 17 pages)"}
{"Year": 1999, "Title": "Michael Dorna. The ADT Package for the Verbmobil Interface Term. Universit\u00e4t Stuttgart. Verbmobil Report 104X. July 1999.  (Postscript, 47 pages)   (HTML Version)"}
{"Year": 1998, "Title": "Johan Bos, Bianka Buschbeck-Wolf, Michael Dorna, and C. J. Rupp. Managing Information at Linguistic Interfaces. In Proceedings of the 17th International Conference on Computational Linguistics (COLING-ACL '98), Montreal, Canada. August 1998.  (Postscript, 7 pages)"}
{"Year": 1998, "Title": "Bianka Buschbeck-Wolf. Restricting Bidirectional Translation Correspondences to the Appropriate Context. In Proceedings of the 8th EURALEX International Congress,Li\ufffdge, Belgium. August, 1998. (Postscript, 10 pages)"}
{"Year": 1998, "Title": "Bianka Buschbeck-Wolf. Using Templates to Encode Transfer Rules Universit\u00e4t Stuttgart. Verbmobil Report 229. October, 1998. (Postscript, 68 pages)"}
{"Year": 1998, "Title": "Bianka Buschbeck-Wolf and Michael Dorna. Quality and Robustness in MT - a Balancing Act In Proceedings of the Third International Conference of the Association for Machine Translation in the Americas (AMTA-98), Langhorne, Pennsylvania. October, 1998. \u00a9 Springer, LNCS series  (Postscript, 10 pages)"}
{"Year": 1998, "Title": "Michael Dorna. The ADT Package for the Verbmobil Interface Term. Universit\u00e4t Stuttgart. Verbmobil Report 104X. October 1998.  (Postscript, 47 pages)"}
{"Year": 1998, "Title": "Michael Dorna, Anette Frank, Josef van Genabith, and Martin C. Emele. Syntactic and Semantic Transfer with F-Structures. In Proceedings of the 17th International Conference on Computational Linguistics (COLING-ACL '98), Montreal, Canada. August 1998.  (Postscript, 7 pages)"}
{"Year": 1998, "Title": "Martin C. Emele and Michael Dorna. Ambiguity Preserving Machine Translation using Packed Representations. In Proceedings of the 17th International Conference on Computational Linguistics (COLING-ACL '98), Montreal, Canada. August 1998.  (Postscript, 7 pages)"}
{"Year": 1998, "Title": "Tsutomu Fujinami and Christine Nanz.  The light verb constructions in Japanese  Verbmobil Report 221. March 1998.  (Postscript, 37 pages)"}
{"Year": 1997, "Title": "Bianka Buschbeck-Wolf. Resolution on Demand. Universit\u00e4t Stuttgart. Verbmobil Report 196. May 1997.  (Postscript, 40 pages)"}
{"Year": 1997, "Title": "Bianka Buschbeck-Wolf and Michael Dorna. Using Hybrid Methods and Resources in Semantic-based Transfer. In Proceedings of the 2nd International Conference \"Recent Advances in Natural Language Processing\" (RANLP'97), Tzigov Chark, Bulgaria, September 1997.  (Postscript, 8 pages)"}
{"Year": 1997, "Title": "Tsutomu Fujinami. Combining situated reasoning with semantic transfer minimally. In Proceedings of Spoken Language Translation Workshop (ACL/EACL 97), Madrid, Spain, July 1997. (Postscript, 2 pages)"}
{"Year": 1997, "Title": "Tsutomu Fujinami and Christine Nanz. The 101 Translation Problems between Japanese and German/English. Verbmobil Report 199. July 1997.  (Postscript, 46 pages)"}
{"Year": 1997, "Title": "Christian Lieske, Johan Bos, Martin Emele, Bj\u00f6rn Gamb\ufffdck and CJ Rupp. Giving Prosody a Meaning. In Proceedings of EuroSpeech'97. September 1997.  (Postscript, 4 pages)"}
{"Year": 1996, "Title": "Michael Dorna. The ADT Package for the Verbmobil Interface Term. Universit\u00e4t Stuttgart. Verbmobil Report 104. July 1996.  (Postscript, 40 pages)   (HTML Version)"}
{"Year": 1996, "Title": "Michael Dorna and Martin Emele. \"Semantic-based Transfer\". In Proceedings of the 16th International Conference on Computational Linguistics (COLING-96), Copenhagen, pp. 316-321. August 1996.  (Postscript, 6 pages)"}
{"Year": 1996, "Title": "Michael Dorna and Martin Emele. \"Efficient Implementation of a Semantic-based Transfer Approach\". In Proceedings of the 12th European Conference on Artificial Intelligence (ECAI-96), Budapest, pp. 567-571. August 1996.  (Postscript, 5 pages)."}
{"Year": 1996, "Title": "Tsutomu Fujinami, Martin Emele and Christine Nanz. The Transfer Module for Japanese. Verbmobil Memo 103. May 1996.  (Postscript, 92 pages)"}
{"Year": 1996, "Title": "Michael Schiehlen. \"Semantic Construction from Parse Forests\". In  Proceedings of the 16th International Conference on Computational Linguistics (COLING-96), Copenhagen, pp. 907-912. August 1996.  (Postscript, 6 pages)."}
{"Year": 1996, "Title": "Kei Yoshimoto and Christine Nanz. A study in transfer Japanese-English. Verbmobil-Report 101. Universit\u00e4t Stuttgart. February 1996.  (Postscript, 20 pages)."}
{"Year": 1995, "Title": "Transfer in the Verbmobil Demonstrator. Verbmobil-Report 147. IAI Saarbr\u00fccken, IBM Deutschland Informationssysteme GmbH, Universit\u00e4t Stuttgart, Universit\u00e4t T\u00fcbingen. August 1995.  (Postscript, 135 pages)."}
{"Year": 1995, "Title": "Ann Copestake. Semantic Transfer in Verbmobil. Verbmobil-Report 93. University of Stuttgart and CSLI. Stanford. August 1995.  (Postscript, 44 pages)."}
{"Year": 1995, "Title": "Mariana Damova. Adverbs in the Transfer Module of MDS. Verbmobil-Report 100. Universit\u00e4t Stuttgart. December 1995.  (Postscript, 30 pages)."}
{"Year": 1995, "Title": "Kurt Eberle. Zu einer Semantik f\u00fcr Dialogverstehen und \u00dcbersetzung. Verbmobil-Report 83. Universit\u00e4t Stuttgart. Juni 1995.  (Postscript, 61 pages)."}
{"Year": 1995, "Title": "Helmut Schmid. Statistische Disambiguierung von Pr\u00e4positionen f\u00fcr den Transfer. Verbmobil Memo 87. Universit\u00e4t Stuttgart. Februar 1995.  (Postscript, 12 pages)."}
{"Year": 1994, "Title": "Michael Dorna, Kurt Eberle, Martin Emele, C.J. Rupp. Semantik-orientierter rekursiver Transfer in HPSG am Beispiel des Referenzdialogs. Verbmobil-Report 39. Universit\u00e4t Stuttgart. November 1994.  (Postscript, 22 pages)."}
{"Year": 1994, "Title": "Jonas Kuhn. Die Behandlung von Funktionsverbgef\u00fcgen in einem HPSG-basierten \u00dcbersetzungsansatz. Verbmobil Report 66. Universit\u00e4t Stuttgart. Dezember 1994.  (Postscript, 69 pages)."}
