{"Year": 1994, "Title": " Wigner Distribution in Speech Research. Master thesis by Wolfgang Wokurek (in German), papers by Grzegorz Dogil, Wolfgang Wokurek, and Krzysztof Marasek (in English), and a bibliography."}
{"Year": 1995, "Title": " Sprachentst\u00f6rung. Doctoral Dissertation, University of Vienna, 1994 by Wolfgang Wokurek (in German with abstract in English). Full title: Sprachentst\u00f6rung unter Verwendung eines Lautklassendetektors (Speech enhancement using a sound class detector)."}
{"Year": 1995, "Title": " Word Stress. Master thesis by Stefan Rapp (in German) and papers mostly by Grzegorz Dogil, Michael Jessen, and Gabriele Scharf (in English)."}
{"Year": 1995, "Title": " Language and Speech Pathology. Master theses by Gabriele Scharf and by J\u00f6rg Mayer (in German) and papers by Hermann Ackermann, Ingo Hertrich, J\u00fcrgen Konczak, and J\u00f6rg Mayer (mostly in German)."}
{"Year": 1997, "Title": " Tense versus Lax Obstruents in German. Revised and expanded version of Ph.D. Dissertation, Cornell University 1996 by Michael Jessen (in English). Full title: Phonetics and phonology of the tense and lax obstruents in German."}
{"Year": 1997, "Title": " Electroglottographic Description of Voice Quality. Habilitationsschrift, University of Stuttgart, by Krzysztof Marasek (in English)."}
{"Year": 1997, "Title": " Aphasie und Kernbereiche der Grammatiktheorie (Aphasia and core domains in the theory of grammar). Doctoral Dissertation, University of Stuttgart, by Annegret Bender (in German with abstract in English)."}
{"Year": 1997, "Title": " Intonation und Bedeutung (Intonation and meaning). Doctoral Dissertation, University of Stuttgart, by J\u00f6rg Mayer (in German with summary in English)."}
{"Year": 1997, "Title": " Koartikulation und glottale Transparenz (Coarticulation and glottal transparency). Doctoral Dissertation, University of Bielefeld, by Kerstin Vollmer (in German with abstract in English)."}
{"Year": 1997, "Title": " Der TFS-Repr\u00e4sentationsformalismus und seine Anwendung in der maschinellen Sprachverarbeitung (The TFS Representation Formalism and its Application to Natural Language Processing). Doctoral Dissertation, University of Stuttgart, by Martin C. Emele (in German with summary in English)."}
{"Year": 1998, "Title": " Automatisierte Erstellung von Korpora f\u00fcr die Prosodieforschung (Automated generation of corpora for prosody research). Doctoral Dissertation, University of Stuttgart, by Stefan Rapp (in German with abstract in English)."}
{"Year": 1998, "Title": " Theoriebasierte Modellierung der deutschen Intonation f\u00fcr die Sprachsynthese (Theory-based modelling of German intonation for speech synthesis). Doctoral Dissertation, University of Stuttgart, by Gregor M\u00f6hler (in German with abstract in English)."}
{"Year": 1998, "Title": " Inducing Lexicons with the EM Algorithm. Papers by M. Rooth, S. Riezler, D. Prescher, S. Schulte im Walde, G. Carroll, F. Beil (in English)."}
{"Year": 1999, "Title": " Probabilistic Constraint Logic Programming. Doctoral Dissertation, University of Stuttgart, by Stefan Riezler (in English)."}
{"Year": 1999, "Title": " Timing bei Dysarthrophonie (Timing in Dysarthria). Doctoral Dissertation, University of Stuttgart, by Gabriele Scharf (in German with abstract in English)."}
{"Year": 1999, "Title": " Semantikkonstruktion (Semantic Construction). Doctoral Dissertation, University of Stuttgart, by Michael Schiehlen (in German with abstract in English)."}
{"Year": 2000, "Title": " YAP: Parsing and Disambiguation with Feature-Based Grammars. Doctoral Dissertation, University of Stuttgart, by Helmut Schmid (in English)."}
{"Year": 2000, "Title": " Semantikbasierter Transfer - Maschinelle \u00dcbersetzung auf Mengen linguistischer Constraints. Doctoral Dissertation, University of Stuttgart, by Michael Dorna (in German)."}
{"Year": 2000, "Title": " The Contribution of Intonation to the Perception of Foreign Accent. Doctoral Dissertation, University of Stuttgart, by Matthias Jilka (in English)."}
{"Year": 2000, "Title": " Research Papers from the Phonetics Lab. Contributions by Kathrin Cla\u00dfen, Grzegorz Dogil, Michael Jessen, Bernd M\u00f6bius, Karin M\u00fcller, Detlef Prescher and Wolfgang Wokurek (most papers in English)."}
{"Year": 2001, "Title": " Automatische Segmentierung, Verwaltung und Abfrage von Korpora gesprochener Sprache (Automated Segmentation, Administration and Retrieval of Spoken Language Corpora). Doctoral Dissertation, University of Stuttgart, by Marcus L. Fach (in German with summary in English)."}
{"Year": 2001, "Title": " Topics in the Clausal Syntax of German. Doctoral Dissertation, University of Stuttgart, by Judith Berman (in English)."}
{"Year": 2001, "Title": " Formal and Computational Aspects of Optimality-Theoretic Syntax. Doctoral Dissertation, University of Stuttgart, by Jonas Kuhn (in English)."}
{"Year": 2001, "Title": " German and Multilingual Speech Synthesis. Habilitationsschrift, University of Stuttgart, by Bernd M\u00f6bius (in English)."}
{"Year": 2002, "Title": " The Automatic Acquisition of Lexical Information from Portuguese Text Corpora with a Probabilistic Context-free Grammar. Doctoral Dissertation, University of Stuttgart, by Erika Fonseca de Lima (in English)."}
{"Year": 2002, "Title": " EM-basierte maschinelle Lernverfahren f\u00fcr nat\u00fcrliche Sprachen (EM-Based Maschine Learning in Natural Language Processing). Doctoral Dissertation, University of Stuttgart, by Detlef Prescher (in German with summary in English). "}
{"Year": 2002, "Title": " Probabilistic Syllable Modeling Using Unsupervised and Supervised Learning Methods. Doctoral Dissertation, University of Stuttgart, by Karin M\u00fcller (in English)."}
{"Year": 2002, "Title": " Ein Suchwerkzeug f\u00fcr syntaktisch annotierte Textkorpora. Doctoral Dissertation, University of Stuttgart, by Wolfgang Lezius (in German with summary in English)."}
{"Year": 2003, "Title": " Implementing and DocumentingLarge-Scale Grammars - German LFG. Doctoral Dissertation, Universityof Stuttgart, by Stefanie Dipper (in English with summary in German)."}
{"Year": 2003, "Title": " Experiments on the AutomaticInduction of German Semantic Verb Classes. Doctoral Dissertation, University of Stuttgart, by Sabine Schulte im Walde (in English)."}
{"Year": 2003, "Title": " Off-line (and On-line) TextAnalysis for Computational Lexicography. Doctoral Dissertation, University of Stuttgart, by Hannah Kermes (in English)."}
{"Year": 2004, "Title": " Phrasenstruktur im Gehirn: neuroanatomischeKorrelate syntaktischer Konstituentenanalyse. Doctoral Dissertation, University of Stuttgart, by Inga Frese (in German with summary in English)."}
{"Year": 2004, "Title": " Eine Methodologie zur korpusbasierten Generierung gesprochener Sprache. Doctoral Dissertation, University of Stuttgart, by Martin Haase (in German with summary in English)."}
{"Year": 2004, "Title": " Ein computerlinguistisches Lexikon als komplexes System. Doctoral Dissertation, University ofStuttgart, by Arne Fitschen (in German with summary in English)."}
{"Year": 2005, "Title": " Experiments on the Predictionof Prosodic Phrasing for German Text-to-Speech Synthesis. Doctoral Dissertation, University of Stuttgart, by Michaela Atterer (in English)."}
{"Year": 2006, "Title": " Categorical Grammar as aBasis for the Semantic Analysis of Coordination and Ellipsis. Habilitationsschrift, University of Stuttgart, by Michael Schiehlen (in English)."}
{"Year": 2006, "Title": " Context Dependence in ModalConstructions. Doctoral Dissertation, Reprint, University ofStuttgart, by Anette Frank (in English)."}
{"Year": 2007, "Title": " Combining DeterministicProcessing with Ambiguity-Awareness - The Case of Quantifying NounGroups in German. Doctoral Dissertation, University of Stuttgart, byKristina Spranger (in English)."}
{"Year": 2007, "Title": " Prosodische unddysprosodische Variation linguistischer und paralinguistischerFunktionen im spontansprachlichen Dialog. Doctoral Dissertation, University of Stuttgart, by Kathrin Cla\u00dfen (in German with summary in English)."}
{"Year": 2007, "Title": " Disambiguation for aLinguistically Precise German Parser. Doctoral Dissertation, University of Stuttgart by Martin Forst (in English)."}
{"Year": 2008, "Title": " Brain Regulation of Language: Neuroimaging of Syntactic and Prosodic Processing. Doctoral Dissertation, University of Stuttgart, by Giuseppina Rota (in in English)."}
{"Year": 2008, "Title": " The Components of Focus and their Use in Annotating Informnation Structure. Doctoral Dissertation, University of Stuttgart, by Arndt Riester (in English)."}
